# Generated by Django 4.2.13 on 2024-05-18 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_survey_user_is_locked_surveyresult_payment_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cards', to=settings.AUTH_USER_MODEL)),
                ('registered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('transfer_date', models.DateField(auto_now_add=True)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner_transfers', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_owner_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='package',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='answer',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='cleanliness_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='facility_condition_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='service_satisfaction_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='update_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FamilyMember',
        ),
    ]
