# Generated by Django 4.2.13 on 2024-05-26 10:30

import ckeditor.fields
import cloudinary.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_accesscard_housetransfer_remove_feedback_is_resolved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('tang', ckeditor.fields.RichTextField()),
                ('type', models.CharField(choices=[('1', 'Can ho loai 1'), ('2', 'Can ho loai 2')], default='2', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('nameContract', ckeditor.fields.RichTextField()),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.apartment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResidentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('cccd', models.CharField(max_length=50, unique=True)),
                ('sdt', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Cho xu ly'), ('pass', 'Xu ly thanh cong')], default='pending', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('nameService', ckeditor.fields.RichTextField()),
                ('priceService', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('surveyForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.surveyform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('answer', models.TextField()),
                ('surveyForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='courses.surveyform')),
                ('surveyQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.surveyquestion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TuDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.RemoveField(
            model_name='housetransfer',
            name='new_owner',
        ),
        migrations.RemoveField(
            model_name='housetransfer',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accesscard',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='package',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='package',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Momo pay'), ('vnpay', 'vn pay')], default='momo', max_length=20),
        ),
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('waiting', 'Cho nhan hang'), ('received', 'Da nhan hang')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.bill'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chua thanh toan'), ('pass', 'Da thanh toan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'quan tri vien'), ('resident', 'dan cu')], default='resident', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='HouseTransfer',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyResult',
        ),
        migrations.AddField(
            model_name='tudo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tudos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentfamily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hop_dong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesscard',
            name='resident_family',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.residentfamily'),
        ),
        migrations.AddField(
            model_name='bill',
            name='service',
            field=models.ManyToManyField(related_name='hoa_don', to='courses.service'),
        ),
        migrations.AddField(
            model_name='package',
            name='tuDo',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='courses.tudo'),
        ),
    ]
