# Generated by Django 4.2.13 on 2024-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20240526_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='soNha',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
