# Generated by Django 4.2.13 on 2024-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_apartment_sonha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='contract',
            name='deposits',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='type',
            field=models.CharField(choices=[('1', 'Căn hộ cao cấp'), ('2', 'Căn hộ trung cấp'), ('3', 'Căn hộ thông thường'), ('4', 'Căn hộ studio'), ('5', 'Căn hộ officetel')], default='1', max_length=20),
        ),
    ]
