# Generated by Django 4.2.13 on 2024-05-29 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_payment_user_contract_deposits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='name',
        ),
    ]
