# Generated by Django 4.2.13 on 2024-05-29 08:00

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_apartment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_image',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tuDo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package', to='courses.tudo'),
        ),
    ]
