# Generated by Django 4.2.13 on 2024-05-29 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_bill_bill_image_payment_payment_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='surveyform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyForm', to=settings.AUTH_USER_MODEL),
        ),
    ]
