# Generated by Django 4.2.13 on 2024-05-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_user_tudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tudo',
            name='user',
        ),
    ]
