# Generated by Django 4.2.13 on 2024-06-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_bill_user_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='courses.bill'),
        ),
    ]
